export const SampleData = Object.freeze({
  // Sample data to autopopulate form in Test envs
  business: {
    name: 'LTO SOFTWARE CONSULTING INC.',
    addressLine1: '123 Fake st',
    addressLine2: 'West',
    city: 'Victoria',
    province: 'BC',
    postalCode: 'VXX 2YY'
  },
  primaryContact: {
    contactType: 'PRIMARY',
    firstName: 'Lucas',
    lastName: 'O\'Neil',
    phone1: '555-555-5555',
    phone2: '777-777-7777',
    email: 'fake@email.ccc'
  },
  covidContact: {
    contactType: 'COVID_COORDINATOR',
    firstName: 'Jane',
    lastName: 'Smith',
    phone1: '666-666-6666',
    phone2: '',
    email: 'no@yes.com'
  },
  location: {
    mineNumber: '1234',
    startDate: '2020-05-22',
    endDate: '2020-05-29',
    city: 'Victoria, BC',
    numberOfWorkers: '20',
    accTents: true,
    tentDetails: 'Down the road 10km',
    accMotel: true,
    motelName: 'Motel 6',
    motelAddressLine1: '456 Some St',
    motelAddressLine2: '',
    motelCity: 'Prince George',
    motelProvince: 'BC',
    motelPostalCode: 'PGP GPG',
    accWorkersHome: true
  },
  attestation: {}
});


export const RandomCities = Object.freeze([
  'Victoria',
  'Kelowna',
  'Abbotsford',
  'White Rock',
  'Nanaimo',
  'Kamloops',
  'Chilliwack',
  'Prince George',
  'Vernon',
  'Courtenay',
  'Campbell River',
  'Penticton',
  'Mission',
  'Parksville',
  'Duncan',
  'Ladner',
  'Tsawwassen',
  'Port Alberni',
  'Fort St. John',
  'Cranbrook',
  'Squamish',
  'Terrace',
  'Salmon Arm',
  'Trail-Fruitvale',
  'Powell River',
  'Quesnel',
  'Aldergrove',
  'Prince Rupert',
  'Dawson Creek',
  'Nelson',
  'Ladysmith',
  'Williams Lake',
  'Sooke',
  'Gibsons',
  'Castlegar',
  'Sechelt',
  'Summerland',
  'Whistler',
  'Shawnigan-Mill Bay',
  'Duck Lake',
  'Revelstoke',
  'Kitimat',
  'Smithers',
  'Merritt',
  'Oliver',
  'Creston',
  'Armstrong',
  'Fernie',
  'Peachland',
  'Osoyoos',
  'Kimberley',
  'Dallas',
  'Hope',
  'Grand Forks',
  'Kent',
  'Port Hardy',
  'Cumberland',
  'Cobble Hill',
  'Aldergrove East',
  'Sparwood',
  'Fort Nelson',
  'Mackenzie',
  'Golden',
  'Rossland',
  'Chemainus',
  'Lake Cowichan',
  'Enderby',
  'Invermere',
  'Princeton',
  'Cowichan Bay',
  'Chase',
  'Okanagan Falls',
  'Houston',
  'Port McNeill',
  'Tumbler Ridge',
  'Vanderhoof',
  'Blind Bay',
  'Pemberton',
  'Rayleigh',
  'Burns Lake',
  'Roberts Creek',
  'One Hundred Mile House',
  'Sicamous',
  'Elkford',
  'Rosedale',
  'Keremeos',
  'Cedar',
  'Ucluelet',
  'Lillooet',
  'Fort St. James',
  'Puntledge',
  'Crofton',
  'Lions Bay',
  'Lumby',
  'Harrison Hot Springs',
  'Logan Lake',
  'Telkwa',
  'Fairwinds',
  'Salmo'
]);
