const CONTACT_TYPE_PRIMARY = 'PRIMARY';
const CONTACT_TYPE_COVID = 'COVID_COORDINATOR';
const CONTACT_TYPES = [CONTACT_TYPE_PRIMARY, CONTACT_TYPE_COVID];

const SLEEPING_AREA_TYPE_SINGLE = 'SINGLE';
const SLEEPING_AREA_TYPE_SHARED = 'SHARED';
const SLEEPING_AREA_TYPES = [SLEEPING_AREA_TYPE_SINGLE, SLEEPING_AREA_TYPE_SHARED];

module.exports = Object.freeze({
  SLUG: 'minesattestations',
  PREFIX: 'mxattstn',
  INITIAL_STATUS_CODE: 'SUBMITTED',
  CONTACT_TYPE_PRIMARY: CONTACT_TYPE_PRIMARY,
  CONTACT_TYPE_COVID: CONTACT_TYPE_COVID,
  CONTACT_TYPES: CONTACT_TYPES,
  SLEEPING_AREA_TYPE_SINGLE: SLEEPING_AREA_TYPE_SINGLE,
  SLEEPING_AREA_TYPE_SHARED: SLEEPING_AREA_TYPE_SHARED,
  SLEEPING_AREA_TYPES: SLEEPING_AREA_TYPES,
  UUID_REGEX: '^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$',
  CONFIRMATION_ID_REGEX: '^[0-9A-Fa-f]{8}$'
});
